minecraft:
  image: colincoleman/minecraft-docker:latest
  restart: always
  ports:
    - "25565:25565"
  volumes:
    - ./data:/home/minecraft/data
  environment:
    - EULA=true
    - JAVAPARAMS=-Xmx4G -Xms4G